// Code generated by "callbackgen -type Stream"; DO NOT EDIT.

package bitget

import ()

func (s *Stream) OnBooksEvent(cb func(o BookEvent)) {
	s.booksEventCallbacks = append(s.booksEventCallbacks, cb)
}

func (s *Stream) EmitBooksEvent(o BookEvent) {
	for _, cb := range s.booksEventCallbacks {
		cb(o)
	}
}
